# Generated by Django 3.2.6 on 2021-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField(default=0)),
                ('game_name', models.CharField(max_length=300)),
                ('pretty_game_name', models.CharField(max_length=300)),
                ('game_id', models.IntegerField(default=0)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('normalend', models.BooleanField(default=True)),
                ('concede', models.BooleanField(default=False)),
                ('unranked', models.BooleanField(default=False)),
                ('elo_win', models.IntegerField(default=0)),
                ('elo_penalty', models.IntegerField(default=0)),
                ('elo_after', models.IntegerField(default=0)),
                ('players', models.CharField(max_length=500)),
                ('player_names', models.CharField(max_length=500)),
                ('scores', models.CharField(max_length=500)),
                ('ranks', models.CharField(max_length=500)),
            ],
        ),
    ]
