# Generated by Django 3.2.6 on 2021-09-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesByPlayerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='table_id',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
