# Generated by Django 3.2.6 on 2021-09-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20210905_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesbyplayermodel',
            old_name='player',
            new_name='player_details',
        ),
    ]
