# Generated by Django 3.2.6 on 2021-09-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_rename_player_gamesbyplayermodel_player_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesbyplayermodel',
            name='player_details',
        ),
        migrations.AddField(
            model_name='gamesbyplayermodel',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
    ]
