# The list of games and their name and pretty names can be found by
# parsing/regexping https://en.doc.boardgamearena.com/Help
pretty_game_names = {
    "thirteenclues": "13 Clues",
    "sechsnimmt": "6 nimmt!",
    "sevenwonders": "7 Wonders",
    "sevenwondersduel": "7 Wonders Duel",
    "eightmastersrevenge": "8 Master's Revenge",
    "ninetynineaddition": "99 (addition card game)",
    "ninetynine": "99 (trick-taking card game)",
    "fistfulofgold": "A Fistful of Gold",
    "abalone": "Abalone",
    "abyss": "Abyss",
    "alhambra": "Alhambra",
    "alveole": "Alveole",
    "amyitis": "Amyitis",
    "apocalypseazcc": "Apocalypse at the Zoo of Carson City",
    "armadora": "Armadöra",
    "assyria": "Assyria",
    "automobiles": "Automobiles",
    "backgammon": "Backgammon",
    "balloonpop": "Balloon Pop!",
    "bandido": "Bandido",
    "barbu": "Barbu",
    "battleoflits": "Battle of LITS",
    "battlesheep": "Battle Sheep",
    "battleship": "Battleships Pencil &amp; Paper",
    "belote": "Belote",
    "beyondthesun": "Beyond the Sun",
    "bids": "Bids",
    "bigtimesoccer": "Big Time Soccer",
    "biyi": "Biyi",
    "blaze": "Blaze",
    "blooms": "Blooms",
    "blueskies": "Blue Skies",
    "bobail": "Bobail",
    "bombay": "Bombay",
    "boomerangaustralia": "Boomerang: Australia",
    "briscola": "Briscola",
    "bug": "Bug",
    "bubbleepop": "Bubblee Pop",
    "butterfly": "Butterfly",
    "buttons": "Buttons",
    "cacao": "Cacao",
    "cantstop": "Can't Stop",
    "caravan": "Caravan",
    "carcassonne": "Carcassonne",
    "carcassonnehuntersandgatherers": "Carcassonne: Hunters &amp; Gatherers",
    "cardiceo": "Cardiceo",
    "caribbeanallfours": "Caribbean All Fours",
    "carnegie": "Carnegie",
    "caylus": "Caylus",
    "celestia": "Celestia",
    "chakra": "Chakra",
    "checkers": "Checkers",
    "chess": "Chess",
    "chinagold": "China Gold",
    "chinesecheckers": "Chinese Checkers",
    "cinco": "Cinco",
    "circleoflife": "Circle of Life",
    "cityofthebigshoulders": "City of the Big Shoulders",
    "clansofcaledonia": "Clans of Caledonia",
    "codexnaturalis": "CODEX Naturalis",
    "coinche": "Coinche",
    "colorpop": "Color Pop",
    "coloretto": "Coloretto",
    "coltexpress": "Colt Express",
    "consonar": "Con Sonar!",
    "concept": "Concept",
    "connectfour": "Connect Four",
    "connectsix": "Connect6",
    "conspiracy": "Conspiracy",
    "coupcitystate": "Coup",
    "crazyfarmers": "Crazy Farmers",
    "cribbage": "Cribbage",
    "cubirds": "CuBirds",
    "darkagent": "Dark Agent",
    "detectivepoker": "Detective Poker",
    "diams": "Diam's",
    "diceforge": "Dice Forge",
    "dicehospital": "Dice Hospital",
    "dicesummoners": "Dice Summoners",
    "dingosdreams": "Dingo's Dreams",
    "dinosaurteaparty": "Dinosaur Tea Party",
    "djambi": "Djambi",
    "dodo": "Dodo",
    "downforce": "Downforce",
    "draftosaurus": "Draftosaurus",
    "dragoncastle": "Dragon Castle",
    "dragonkeeper": "Dragon Keeper: The Dungeon",
    "dragonline": "Dragon Line",
    "dragonheart": "Dragonheart",
    "dragonwood": "Dragonwood",
    "dungeonpetz": "Dungeon Petz",
    "dungeonroll": "Dungeon Roll",
    "dungeontwister": "Dungeon Twister",
    "elfenland": "Elfenland",
    "eminentdomain": "Eminent Domain",
    "emdomicrocosm": "Eminent Domain: Microcosm",
    "akeruption": "Eruption",
    "evogamenoname": "Evo: The \"Game no Name\"",
    "northwestpassage": "Expedition: Northwest Passage",
    "explorationwarzone": "Exploration: Warzone",
    "finity": "Finity",
    "flamingpyramids": "Flaming Pyramids",
    "fleet": "Fleet",
    "florenzacardgame": "Florenza: The Card Game",
    "fluxx": "Fluxx",
    "forsale": "For Sale",
    "forbiddenisland": "Forbidden Island",
    "fourcolorcards": "Four Color Cards",
    "frenchtarot": "French Tarot",
    "gaia": "Gaia",
    "gearnpiston": "Gear &amp; Piston",
    "classicgo": "Go",
    "gonutsfordonuts": "Go Nuts for Donuts",
    "goldwest": "Gold West",
    "gomoku": "Gomoku",
    "gopher": "Gopher",
    "gorami": "GORami",
    "gosu": "Gosu",
    "grandbazaar": "Grand Bazaar",
    "grosstarock": "Grosstarock",
    "gyges": "Gygès",
    "hacktrick": "Hack Trick",
    "haggis": "Haggis",
    "haiclue": "Haiclue",
    "hanabi": "Hanabi",
    "handandfoot": "Hand and Foot",
    "happycity": "Happy City",
    "hardback": "Hardback",
    "hawaii": "Hawaii",
    "hearts": "Hearts",
    "herrlof": "Herrlof",
    "herooj": "Herooj",
    "hex": "Hex",
    "hive": "Hive",
    "hoarders": "Hoarders",
    "homesteaders": "Homesteaders",
    "escapefromthehiddencastle": "HUGO",
    "hungariantarokk": "Hungarian Tarokk",
    "hypnosia": "Hypnosia",
    "icecoldicehockey": "Ice Cold Ice Hockey",
    "illustori": "Illustori",
    "intheyearofthedragon": "In The Year of the Dragon",
    "incangold": "Incan Gold",
    "innovation": "Innovation",
    "isaac": "Isaac",
    "iwari": "Iwari",
    "jaipur": "Jaipur",
    "jekyllvshide": "Jekyll vs. Hyde",
    "jumpgate": "Jump Gate",
    "justdesserts": "Just Desserts",
    "k2": "K2",
    "kabaleo": "Kabaleo",
    "kahuna": "Kahuna",
    "kalah": "Kalah",
    "kami": "Kami",
    "keyflower": "Keyflower",
    "khronos": "Khronos",
    "kingofthepitch": "King of the Pitch",
    "kingdombuilder": "Kingdom Builder",
    "kingdomino": "Kingdomino",
    "klaverjassen": "Klaverjassen",
    "koikoi": "Koi-Koi",
    "koryo": "Koryŏ",
    "kqj": "KQJ",
    "krosmasterarena": "Krosmaster Arena",
    "krosmasterblast": "Krosmaster Blast",
    "lagranja": "La Granja",
    "ledernierpeuple": "Le Dernier Peuple",
    "inventors": "Legendary Inventors",
    "lettertycoon": "Letter Tycoon",
    "lewisclark": "Lewis &amp; Clark",
    "libertalia": "Libertalia",
    "linesofaction": "Lines of Action",
    "logger": "Logger",
    "lox": "Lords of Xidit",
    "lostcities": "Lost Cities",
    "arnak": "Lost Ruins of Arnak",
    "loveletter": "Love Letter",
    "luckynumbers": "Lucky Numbers",
    "luxor": "Luxor",
    "machiavelli": "Machiavelli",
    "madeira": "Madeira",
    "mammalath": "Mammalath",
    "mapmaker": "Mapmaker: The Gerrymandering Game",
    "marcopolotwo": "Marco Polo II: In the Service of the Khan",
    "marrakech": "Marrakech",
    "marram": "Marram",
    "martiandice": "Martian Dice",
    "mattock": "Mattock",
    "medina": "Medina",
    "meadow": "Medo",
    "metromania": "Metromania",
    "mijnlieff": "Mijnlieff",
    "monsterfactory": "Monster Factory",
    "mrjack": "Mr. Jack",
    "murusgallicus": "Murus Gallicus",
    "nangaparbat": "Nanga Parbat",
    "nautilus": "Nautilus",
    "neutreeko": "Neutreeko",
    "niagara": "Niagara",
    "nidavellir": "Nidavellir",
    "aknile": "Nile",
    "ninemensmorris": "Nine Men's Morris",
    "nippon": "Nippon",
    "nothanks": "No Thanks!",
    "noirkvi": "Noir: Killer versus Inspector",
    "notalone": "Not Alone",
    "nxs": "NXS",
    "offtherails": "Off the Rails",
    "ohhell": "Oh Hell!",
    "ohseven": "Oh-Seven",
    "onceuponaforest": "Once Upon A Forest",
    "one": "ONE",
    "oriflamme": "Oriflamme",
    "origin": "Origin",
    "outlaws": "Outlaws: Last Man Standing",
    "pi": "P.I.",
    "palace": "Palace",
    "pandamic": "Pandemic",
    "papayoo": "Papayoo",
    "parisconnection": "Paris Connection",
    "patchwork": "Patchwork",
    "pedro": "Pedro",
    "penaltychallenge": "Penalty Challenge",
    "pennypress": "Penny Press",
    "dudo": "Perudo",
    "phat": "Phat",
    "pingimus": "Pingimus",
    "piratenkapern": "Piraten kapern",
    "polis": "Polis: Fight for Hegemony",
    "pontedeldiavolo": "Ponte del Diavolo",
    "potionexplosion": "Potion Explosion",
    "puertorico": "Puerto Rico",
    "pylos": "Pylos",
    "quantik": "Quantik",
    "quantum": "Quantum",
    "quarto": "Quarto",
    "quetzal": "Quetzal",
    "quinque": "Quinque",
    "quoridor": "Quoridor",
    "raceforthegalaxy": "Race for the Galaxy",
    "rage": "Rage",
    "railroadink": "Railroad Ink",
    "rallymangt": "Rallyman: GT",
    "redseven": "Red7",
    "rememberwhen": "Remember When",
    "resarcana": "Res Arcana",
    "restinpeace": "Rest In Peace",
    "reversi": "Reversi",
    "rollforthegalaxy": "Roll for the Galaxy",
    "rolledwest": "Rolled West",
    "russianrailroads": "Russian Railroads",
    "saboteur": "Saboteur",
    "saintpetersburg": "Saint Petersburg",
    "saintpoker": "Saint Poker",
    "santorini": "Santorini",
    "sapiens": "Sapiens",
    "schroedingerscats": "Schrodinger's Cats",
    "seasons": "Seasons",
    "secretmoon": "Secret Moon",
    "senet": "Senet",
    "siam": "Siam",
    "signorie": "Signorie",
    "skat": "Skat",
    "skull": "Skull",
    "smallislands": "Small Islands",
    "sobek": "Sobek",
    "sobektwoplayers": "Sobek 2 players",
    "solarstorm": "Solar Storm",
    "solo": "Solo",
    "solowhist": "Solo Whist",
    "soluna": "Soluna",
    "spades": "Spades",
    "sparts": "Sparts",
    "splendor": "Splendor",
    "spyrium": "Spyrium",
    "squadro": "Squadro",
    "steamworks": "Steam Works",
    "stirfryeighteen": "Stir Fry Eighteen",
    "stoneage": "Stone Age",
    "superfantasybrawl": "Super Fantasy Brawl",
    "sushigo": "Sushi Go!",
    "tablut": "Tablut",
    "takaraisland": "Takara Island",
    "takenoko": "Takenoko",
    "taluva": "Taluva",
    "targi": "Targi",
    "tashkalar": "Tash-Kalar",
    "teatime": "Tea Time",
    "teotihuacan": "Teotihuacan: City of Gods",
    "terramystica": "Terra Mystica",
    "thatslife": "That's Life (or Verflixxt!)",
    "battleforhill": "The Battle for Hill 218",
    "theboss": "The Boss",
    "thebuildersantiquity": "The Builders: Antiquity",
    "thebuilders": "The Builders: Middle Ages",
    "thecrew": "The Crew",
    "thejellymonsterlab": "The Jelly Monster Lab",
    "kingsguild": "The King's Guild",
    "carrara": "The Palaces of Carrara",
    "ruhr": "The Ruhr: A Story of Coal Trade",
    "marcopolo": "The Voyages of Marco Polo",
    "werewolves": "The Werewolves of Miller's Hollow",
    "thermopyles": "Thermopyles",
    "throughtheages": "Through the Ages",
    "throughtheagesnewstory": "Through the Ages: A new Story of Civilization",
    "thurnandtaxis": "Thurn and Taxis",
    "tichu": "Tichu",
    "tiki": "Tiki",
    "timemasters": "Time Masters",
    "tobago": "Tobago",
    "tock": "Tock",
    "toeshambo": "ToeShamBo",
    "tokaido": "Tokaido",
    "tournay": "Tournay",
    "tranquility": "Tranquility",
    "trektwelve": "Trek 12",
    "trekkingtheworld": "Trekking the World",
    "trickoftherails": "Trick of the Rails",
    "troyes": "Troyes",
    "turnthetide": "Turn the tide",
    "twintinbots": "Twin Tin Bots",
    "tzolkin": "Tzolk'in",
    "unclechestnuttablegype": "Uncle Chestnut's Table Gype",
    "unconditionalsurrender": "Unconditional Surrender! World War 2 in Europe",
    "unitedsquare": "United Square",
    "veggiegarden": "Veggie Garden",
    "veletas": "Veletas",
    "veronatwist": "Verona Twist",
    "viamagica": "Via Magica",
    "viticulture": "Viticulture",
    "vultureculture": "Vulture Culture",
    "welcometo": "Welcome To",
    "welcometonewlasvegas": "Welcome To New Las Vegas",
    "whisttwentytwo": "Whist 22",
    "wizard": "Wizard",
    "xiangqi": "Xiangqi",
    "yatzy": "Yahtzee",
    "yinyang": "Yin Yang",
    "yokai": "Yokai",
    "yokohama": "Yokohama",
    "abandonallartichokes": "Abandon All Artichokes",
    "agricola": "Agricola",
    "bang": "BANG!",
    "canosa": "Canosa",
    "dicedtomatoes": "Diced Tomatoes",
    "forex": "For-Ex",
    "harbour": "Harbour",
    "insert": "Insert",
    "lama": "L.L.A.M.A.",
    "lineae": "Lineae",
    "linkage": "Linkage",
    "liverpoolrummy": "Liverpool (Cozy Oaks) Rummy",
    "lostexplorers": "Lost Explorers",
    "newfrontiers": "New Frontiers",
    "onitama": "Onitama",
    "president": "President",
    "roomtwentyfive": "Room 25",
    "senshi": "Senshi",
    "sheepboombah": "Sheep Boom Bah",
    "castlesofburgundy": "The Castles of Burgundy",
    "troyesdice": "Troyes Dice",
    "uptown": "Uptown",
    "zener": "Zener",
    "fifteendays": "15 Days",
    "artdecko": "Art Decko",
    "baolakiswahili": "Bao la Kiswahili",
    "bohnanza": "Bohnanza",
    "boomeranglm": "Boomerang",
    "boomerangeurope": "Boomerang: Europe",
    "boomerangusa": "Boomerang: USA",
    "bossquest": "Boss Quest",
    "burglebros": "Burgle Bros.",
    "calypso": "Calypso",
    "championsofmidgard": "Champions of Midgard",
    "chicagoexpress": "Chicago Express",
    "chocolatefactory": "Chocolate Factory",
    "cicerabigia": "Cicera Bigia",
    "clashofdecks": "Clash of Decks",
    "cloudcity": "Cloud City",
    "coinage": "Coin Age",
    "crazyeights": "Crazy Eights",
    "daihasamishogi": "Dai Hasami Shogi",
    "durak": "Durak",
    "egocentricworld": "Egocentric World",
    "elgrande": "El Grande",
    "epizodiak": "EpiZodiak",
    "factum": "Factum",
    "faifo": "Fai-Fo",
    "geekoutmasters": "Geek Out! Masters",
    "getthemacguffin": "Get the MacGuffin",
    "ginkgopolis": "Ginkgopolis",
    "gravitysuperstar": "Gravity Superstar",
    "guibole": "Guibole",
    "guile": "Guile",
    "hats": "Hats",
    "indianchief": "Indian Chief",
    "riichimahjong": "Japanese (Riichi) Mahjong",
    "kingoftokyo": "King of Tokyo",
    "kulami": "Kulami",
    "magicmaze": "Magic Maze",
    "mahjong": "Mahjong",
    "manhattannewgame": "Manhattan",
    "mantisfalls": "Mantis Falls",
    "martianchess": "Martian Chess",
    "mascarade": "Mascarade",
    "mercadodelisboaste": "Mercado de Lisboa",
    "minnesotawhist": "Minnesota Whist",
    "myfirstcastlepanic": "My First Castle Panic",
    "nainjaune": "Nain Jaune",
    "nicodemus": "Nicodemus",
    "paniclab": "Panic Lab",
    "pinochle": "Pinochle",
    "fixtheteleporter": "Please Fix the Teleporter",
    "texasholdem": "Poker Texas Hold'em",
    "pyramidpoker": "Pyramid Poker",
    "queenskings": "Queens and Kings: A Checkers Game",
    "railwaysoftheworld": "Railways of the World",
    "riftforce": "Riftforce",
    "schwimmen": "Schwimmen",
    "sensei": "Sensei",
    "ninefivetwo": "Sergeant Major",
    "sevens": "Sevens",
    "similo": "Similo",
    "simplicity": "Simplicity",
    "snekagon": "Snekagon",
    "snowtime": "Snow Time",
    "spacebase": "Space Base",
    "spiritsoftheforest": "Spirits of the Forest",
    "talon": "Talon",
    "tapestry": "Tapestry",
    "templari": "Templari",
    "theninedomains": "The Nine Domains",
    "threespot": "Three Spot",
    "thrive": "Thrive",
    "throneandthegrail": "Throne and the Grail",
    "trasteroslocoscrazyauctions": "Trasteros Locos: Crazy Auctions",
    "troggu": "Troggu",
    "volfyirion": "Volfyirion Guilds",
    "watergate": "Watergate",
    "wazabi": "Wazabi",
    "xanadu": "Xanadu",
    "yspahan": "Yspahan"
}


def get_pretty_name(name) -> str:
    if name in pretty_game_names:
        return pretty_game_names[name]
    return name
